// script.js - Dynamic Dashboard

let allWallets = [];
let currentFilter = 'all';

// Load data from JSON file (generated by scraper)
async function loadData() {
    try {
        const response = await fetch('wallets.json');
        if (!response.ok) throw new Error('Data not found');
        const data = await response.json();
        allWallets = data;
        updateDashboard();
    } catch (error) {
        console.error('Error loading data:', error);
        document.getElementById('walletBody').innerHTML = 
            '<tr><td colspan="5" style="text-align:center;color:#888;">No data found. Run scraper first.</td></tr>';
    }
}

function updateDashboard() {
    const filtered = currentFilter === 'all' 
        ? allWallets 
        : allWallets.filter(w => w.chain === currentFilter);
    
    // Update stats
    document.getElementById('count').textContent = allWallets.length;
    document.getElementById('uniqueWallets').textContent = filtered.length;
    
    const totalBal = filtered.reduce((sum, w) => sum + parseFloat(w.balance), 0);
    document.getElementById('totalBalance').textContent = totalBal.toFixed(4);
    document.getElementById('lastUpdate').textContent = new Date().toLocaleString();
    
    // Render table
    const tbody = document.getElementById('walletBody');
    tbody.innerHTML = '';
    
    if (filtered.length === 0) {
        tbody.innerHTML = '<tr><td colspan="5" style="text-align:center;color:#666;">No wallets found for this filter.</td></tr>';
        return;
    }
    
    filtered.forEach((wallet, index) => {
        const row = document.createElement('tr');
        row.innerHTML = `
            <td>${index + 1}</td>
            <td class="address">${wallet.address.slice(0, 10)}...${wallet.address.slice(-6)}</td>
            <td>${wallet.chain.toUpperCase()}</td>
            <td class="balance">${parseFloat(wallet.balance).toFixed(6)}</td>
            <td>${wallet.timestamp || 'N/A'}</td>
        `;
        tbody.appendChild(row);
    });
}

function filterByChain(chain) {
    currentFilter = chain;
    // Update active button style
    document.querySelectorAll('.filters button').forEach(btn => btn.classList.remove('active'));
    event.target.classList.add('active');
    updateDashboard();
}

function filterWallets() {
    const query = document.getElementById('searchInput').value.toLowerCase();
    const filtered = allWallets.filter(w => 
        w.address.toLowerCase().includes(query) || 
        w.chain.toLowerCase().includes(query)
    );
    // Temporarily override display for search
    const tbody = document.getElementById('walletBody');
    tbody.innerHTML = '';
    filtered.forEach((wallet, index) => {
        const row = document.createElement('tr');
        row.innerHTML = `
            <td>${index + 1}</td>
            <td class="address">${wallet.address.slice(0, 10)}...${wallet.address.slice(-6)}</td>
            <td>${wallet.chain.toUpperCase()}</td>
            <td class="balance">${parseFloat(wallet.balance).toFixed(6)}</td>
            <td>${wallet.timestamp || 'N/A'}</td>
        `;
        tbody.appendChild(row);
    });
}

// Search on Enter key
document.getElementById('searchInput').addEventListener('keyup', function(e) {
    if (e.key === 'Enter') filterWallets();
});

// Load data on startup
loadData();

// Auto-refresh every 60 seconds (if you update wallets.json)
setInterval(loadData, 60000);
